version: "3.6"
services:
  backend:
    volumes:
      - ./backend/app:/app
    command: /start-reload.sh
    environment:
      - ENVIRONMENT=dev
    ports:
      - "8080:80"

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"

  pgadmin:
    ports:
      - "5050:80"

  flower:
    ports:
      - "5555:5555"

  locust-master:
    image: locustio/locust:master
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/locust
    env_file:
      - .env
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    command: -f /locust/load_test.py --master -H http://backend:80

  locust-worker:
    image: locustio/locust:master
    volumes:
      - ./locust:/locust
    env_file:
      - .env
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    command: -f /locust/load_test.py --worker --master-host locust-master

networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false
