"""initial create tables

Revision ID: 41521c355323
Revises:
Create Date: 2022-06-05 12:56:46.637163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41521c355323"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical",
        sa.Column("date", sa.DATE, nullable=False),
        sa.Column("growth", sa.REAL, nullable=True),
        sa.Column("country", sa.VARCHAR, nullable=True),
        sa.Column("ticker", sa.VARCHAR, nullable=False),
        sa.Column("name", sa.VARCHAR, nullable=True),
        sa.Column("industry", sa.VARCHAR, nullable=True),
        sa.Column("sector", sa.VARCHAR, nullable=True),
        sa.Column("close", sa.REAL, nullable=True),
        sa.Column("change_percent", sa.REAL, nullable=True),
        sa.Column("volume", sa.REAL, nullable=True),
        sa.Column("turnover_percent", sa.REAL, nullable=True),
        sa.Column("range_percent", sa.REAL, nullable=True),
        sa.Column("year_high_rel", sa.REAL, nullable=True),
        sa.Column("year_low_rel", sa.REAL, nullable=True),
        sa.Column("market_cap", sa.REAL, nullable=True),
        sa.Column("eps", sa.REAL, nullable=True),
        sa.Column("dps", sa.REAL, nullable=True),
        sa.Column("dividend_yield_percent", sa.REAL, nullable=True),
        sa.Column("book_value", sa.REAL, nullable=True),
        sa.Column("pb", sa.REAL, nullable=True),
        sa.Column("ps", sa.REAL, nullable=True),
        sa.Column("pe", sa.REAL, nullable=True),
        sa.Column("peg", sa.REAL, nullable=True),
        sa.Column("pcf", sa.REAL, nullable=True),
        sa.Column("evs", sa.REAL, nullable=True),
        sa.Column("evebitda", sa.REAL, nullable=True),
        sa.Column("evebit", sa.REAL, nullable=True),
        sa.Column("evnopat", sa.REAL, nullable=True),
        sa.Column("ebitda_margin", sa.REAL, nullable=True),
        sa.Column("ebit_margin", sa.REAL, nullable=True),
        sa.Column("profit_margin", sa.REAL, nullable=True),
        sa.Column("revenue_5y_cagr", sa.REAL, nullable=True),
        sa.Column("ebitda_5y_cagr", sa.REAL, nullable=True),
        sa.Column("ebit_5y_cagr", sa.REAL, nullable=True),
        sa.Column("profit_5y_cagr", sa.REAL, nullable=True),
        sa.Column("roe", sa.REAL, nullable=True),
        sa.Column("roa", sa.REAL, nullable=True),
        sa.Column("roce", sa.REAL, nullable=True),
        sa.Column("roic", sa.REAL, nullable=True),
        sa.Column("rod", sa.REAL, nullable=True),
        sa.Column("current_ratio", sa.REAL, nullable=True),
        sa.Column("quick_ratio", sa.REAL, nullable=True),
        sa.Column("cash_ratio", sa.REAL, nullable=True),
        sa.Column("ocf_ratio", sa.REAL, nullable=True),
        sa.Column("wct", sa.REAL, nullable=True),
        sa.Column("de", sa.REAL, nullable=True),
        sa.Column("da", sa.REAL, nullable=True),
        sa.Column("ea", sa.REAL, nullable=True),
        sa.Column("piotroski", sa.SMALLINT, nullable=True),
        sa.Column("altman_z", sa.REAL, nullable=True),
        sa.Column("grade", sa.REAL, nullable=True),
        sa.Column("ownership_percent", sa.REAL, nullable=True),
        sa.Column("ownership_percent_change", sa.REAL, nullable=True),
        sa.Column("put_call_ratio", sa.REAL, nullable=True),
        sa.Column("put_call_ratio_change", sa.REAL, nullable=True),
        sa.Column("ao", sa.REAL, nullable=True),
        sa.Column("rsi", sa.REAL, nullable=True),
        sa.Column("stoch", sa.REAL, nullable=True),
        sa.Column("tsi", sa.REAL, nullable=True),
        sa.Column("uo", sa.REAL, nullable=True),
        sa.Column("cmf", sa.REAL, nullable=True),
        sa.Column("fi", sa.REAL, nullable=True),
        sa.Column("mfi", sa.REAL, nullable=True),
        sa.Column("nvi", sa.REAL, nullable=True),
        sa.Column("adx", sa.REAL, nullable=True),
        sa.Column("adxp", sa.REAL, nullable=True),
        sa.Column("adxn", sa.REAL, nullable=True),
        sa.Column("macd", sa.REAL, nullable=True),
        sa.Column("mi", sa.REAL, nullable=True),
        sa.Column("kdj", sa.REAL, nullable=True),
        sa.Column("pvol", sa.REAL, nullable=True),
        sa.Column("stdev", sa.REAL, nullable=True),
        sa.Column("entropy", sa.REAL, nullable=True),
        sa.Column("skew", sa.REAL, nullable=True),
        sa.Column("kurtosis", sa.REAL, nullable=True),
        sa.Column("sma", sa.REAL, nullable=True),
        sa.Column("ema", sa.REAL, nullable=True),
        sa.Column("kama", sa.REAL, nullable=True),
        sa.Column("bollh", sa.REAL, nullable=True),
        sa.Column("bolll", sa.REAL, nullable=True),
        sa.Column("dch", sa.REAL, nullable=True),
        sa.Column("dcl", sa.REAL, nullable=True),
        sa.Column("kch", sa.REAL, nullable=True),
        sa.Column("kcl", sa.REAL, nullable=True),
        sa.Column("days_since_bullish_cdlbreakaway", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlcounterattack", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdldojistar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdldragonflydoji", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlengulfing", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlhammer", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlhomingpigeon", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlinvertedhammer", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlladderbottom", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdllongline", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlmarubozu", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlmatchinglow", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlmorningdojistar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlonneck", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlpiercing", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlseparatinglines", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdl3whitesoldiers", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdl3inside", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdl3outside", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdl3starsinsouth", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlthrusting", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdltristar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlunique3river", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlxsidegap3methods", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlbreakaway", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlcounterattack", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdldojistar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdldragonflydoji", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlengulfing", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlhammer", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlhomingpigeon", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlinvertedhammer", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlladderbottom", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdllongline", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlmarubozu", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlmatchinglow", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlmorningdojistar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlonneck", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlpiercing", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlseparatinglines", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdl3whitesoldiers", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdl3inside", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdl3outside", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdl3starsinsouth", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlthrusting", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdltristar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlunique3river", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlxsidegap3methods", sa.SMALLINT, nullable=True),
        sa.PrimaryKeyConstraint("ticker", "date"),
    )

    op.create_index(
        op.f("ix_historical_country_date"),
        "historical",
        ["country", "date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_industry"),
        "historical",
        ["country", "industry"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_sector"),
        "historical",
        ["country", "sector"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_close"),
        "historical",
        ["country", "close"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_change_percent"),
        "historical",
        ["country", "change_percent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_volume"),
        "historical",
        ["country", "volume"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_turnover_percent"),
        "historical",
        ["country", "turnover_percent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_range_percent"),
        "historical",
        ["country", "range_percent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_year_high_rel"),
        "historical",
        ["country", "year_high_rel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_year_low_rel"),
        "historical",
        ["country", "year_low_rel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_market_cap"),
        "historical",
        ["country", "market_cap"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_eps"),
        "historical",
        ["country", "eps"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_dps"),
        "historical",
        ["country", "dps"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_dividend_yield_percent"),
        "historical",
        ["country", "dividend_yield_percent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_book_value"),
        "historical",
        ["country", "book_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_pb"), "historical", ["country", "pb"], unique=False
    )
    op.create_index(
        op.f("ix_historical_country_ps"), "historical", ["country", "ps"], unique=False
    )
    op.create_index(
        op.f("ix_historical_country_pe"), "historical", ["country", "pe"], unique=False
    )
    op.create_index(
        op.f("ix_historical_country_peg"),
        "historical",
        ["country", "peg"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_pcf"),
        "historical",
        ["country", "pcf"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_evs"),
        "historical",
        ["country", "evs"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_evebitda"),
        "historical",
        ["country", "evebitda"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_evebit"),
        "historical",
        ["country", "evebit"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_evnopat"),
        "historical",
        ["country", "evnopat"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_ebitda_margin"),
        "historical",
        ["country", "ebitda_margin"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_ebit_margin"),
        "historical",
        ["country", "ebit_margin"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_profit_margin"),
        "historical",
        ["country", "profit_margin"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_revenue_5y_cagr"),
        "historical",
        ["country", "revenue_5y_cagr"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_ebitda_5y_cagr"),
        "historical",
        ["country", "ebitda_5y_cagr"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_ebit_5y_cagr"),
        "historical",
        ["country", "ebit_5y_cagr"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_profit_5y_cagr"),
        "historical",
        ["country", "profit_5y_cagr"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_roe"),
        "historical",
        ["country", "roe"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_roa"),
        "historical",
        ["country", "roa"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_roce"),
        "historical",
        ["country", "roce"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_roic"),
        "historical",
        ["country", "roic"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_rod"),
        "historical",
        ["country", "rod"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_current_ratio"),
        "historical",
        ["country", "current_ratio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_quick_ratio"),
        "historical",
        ["country", "quick_ratio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_cash_ratio"),
        "historical",
        ["country", "cash_ratio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_ocf_ratio"),
        "historical",
        ["country", "ocf_ratio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_wct"),
        "historical",
        ["country", "wct"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_de"), "historical", ["country", "de"], unique=False
    )
    op.create_index(
        op.f("ix_historical_country_da"), "historical", ["country", "da"], unique=False
    )
    op.create_index(
        op.f("ix_historical_country_ea"), "historical", ["country", "ea"], unique=False
    )
    op.create_index(
        op.f("ix_historical_country_piotroski"),
        "historical",
        ["country", "piotroski"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_altman_z"),
        "historical",
        ["country", "altman_z"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_grade"),
        "historical",
        ["country", "grade"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_ownership_percent"),
        "historical",
        ["country", "ownership_percent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_ownership_percent_change"),
        "historical",
        ["country", "ownership_percent_change"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_put_call_ratio"),
        "historical",
        ["country", "put_call_ratio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_put_call_ratio_change"),
        "historical",
        ["country", "put_call_ratio_change"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_ao"), "historical", ["country", "ao"], unique=False
    )
    op.create_index(
        op.f("ix_historical_country_rsi"),
        "historical",
        ["country", "rsi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_stoch"),
        "historical",
        ["country", "stoch"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_tsi"),
        "historical",
        ["country", "tsi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_uo"), "historical", ["country", "uo"], unique=False
    )
    op.create_index(
        op.f("ix_historical_country_cmf"),
        "historical",
        ["country", "cmf"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_fi"), "historical", ["country", "fi"], unique=False
    )
    op.create_index(
        op.f("ix_historical_country_mfi"),
        "historical",
        ["country", "mfi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_nvi"),
        "historical",
        ["country", "nvi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_adx"),
        "historical",
        ["country", "adx"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_adxp"),
        "historical",
        ["country", "adxp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_adxn"),
        "historical",
        ["country", "adxn"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_macd"),
        "historical",
        ["country", "macd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_mi"), "historical", ["country", "mi"], unique=False
    )
    op.create_index(
        op.f("ix_historical_country_kdj"),
        "historical",
        ["country", "kdj"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_pvol"),
        "historical",
        ["country", "pvol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_stdev"),
        "historical",
        ["country", "stdev"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_entropy"),
        "historical",
        ["country", "entropy"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_skew"),
        "historical",
        ["country", "skew"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_kurtosis"),
        "historical",
        ["country", "kurtosis"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_sma"),
        "historical",
        ["country", "sma"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_ema"),
        "historical",
        ["country", "ema"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_kama"),
        "historical",
        ["country", "kama"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_bollh"),
        "historical",
        ["country", "bollh"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_bolll"),
        "historical",
        ["country", "bolll"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_dch"),
        "historical",
        ["country", "dch"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_dcl"),
        "historical",
        ["country", "dcl"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_kch"),
        "historical",
        ["country", "kch"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_kcl"),
        "historical",
        ["country", "kcl"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlbreakaway"),
        "historical",
        ["country", "days_since_bullish_cdlbreakaway"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlcounterattack"),
        "historical",
        ["country", "days_since_bullish_cdlcounterattack"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdldojistar"),
        "historical",
        ["country", "days_since_bullish_cdldojistar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdldragonflydoji"),
        "historical",
        ["country", "days_since_bullish_cdldragonflydoji"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlengulfing"),
        "historical",
        ["country", "days_since_bullish_cdlengulfing"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlhammer"),
        "historical",
        ["country", "days_since_bullish_cdlhammer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlhomingpigeon"),
        "historical",
        ["country", "days_since_bullish_cdlhomingpigeon"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlinvertedhammer"),
        "historical",
        ["country", "days_since_bullish_cdlinvertedhammer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlladderbottom"),
        "historical",
        ["country", "days_since_bullish_cdlladderbottom"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdllongline"),
        "historical",
        ["country", "days_since_bullish_cdllongline"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlmarubozu"),
        "historical",
        ["country", "days_since_bullish_cdlmarubozu"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlmatchinglow"),
        "historical",
        ["country", "days_since_bullish_cdlmatchinglow"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlmorningdojistar"),
        "historical",
        ["country", "days_since_bullish_cdlmorningdojistar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlonneck"),
        "historical",
        ["country", "days_since_bullish_cdlonneck"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlpiercing"),
        "historical",
        ["country", "days_since_bullish_cdlpiercing"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlseparatinglines"),
        "historical",
        ["country", "days_since_bullish_cdlseparatinglines"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdl3whitesoldiers"),
        "historical",
        ["country", "days_since_bullish_cdl3whitesoldiers"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdl3inside"),
        "historical",
        ["country", "days_since_bullish_cdl3inside"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdl3outside"),
        "historical",
        ["country", "days_since_bullish_cdl3outside"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdl3starsinsouth"),
        "historical",
        ["country", "days_since_bullish_cdl3starsinsouth"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlthrusting"),
        "historical",
        ["country", "days_since_bullish_cdlthrusting"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdltristar"),
        "historical",
        ["country", "days_since_bullish_cdltristar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlunique3river"),
        "historical",
        ["country", "days_since_bullish_cdlunique3river"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bullish_cdlxsidegap3methods"),
        "historical",
        ["country", "days_since_bullish_cdlxsidegap3methods"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlbreakaway"),
        "historical",
        ["country", "days_since_bearish_cdlbreakaway"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlcounterattack"),
        "historical",
        ["country", "days_since_bearish_cdlcounterattack"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdldojistar"),
        "historical",
        ["country", "days_since_bearish_cdldojistar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdldragonflydoji"),
        "historical",
        ["country", "days_since_bearish_cdldragonflydoji"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlengulfing"),
        "historical",
        ["country", "days_since_bearish_cdlengulfing"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlhammer"),
        "historical",
        ["country", "days_since_bearish_cdlhammer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlhomingpigeon"),
        "historical",
        ["country", "days_since_bearish_cdlhomingpigeon"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlinvertedhammer"),
        "historical",
        ["country", "days_since_bearish_cdlinvertedhammer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlladderbottom"),
        "historical",
        ["country", "days_since_bearish_cdlladderbottom"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdllongline"),
        "historical",
        ["country", "days_since_bearish_cdllongline"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlmarubozu"),
        "historical",
        ["country", "days_since_bearish_cdlmarubozu"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlmatchinglow"),
        "historical",
        ["country", "days_since_bearish_cdlmatchinglow"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlmorningdojistar"),
        "historical",
        ["country", "days_since_bearish_cdlmorningdojistar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlonneck"),
        "historical",
        ["country", "days_since_bearish_cdlonneck"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlpiercing"),
        "historical",
        ["country", "days_since_bearish_cdlpiercing"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlseparatinglines"),
        "historical",
        ["country", "days_since_bearish_cdlseparatinglines"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdl3whitesoldiers"),
        "historical",
        ["country", "days_since_bearish_cdl3whitesoldiers"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdl3inside"),
        "historical",
        ["country", "days_since_bearish_cdl3inside"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdl3outside"),
        "historical",
        ["country", "days_since_bearish_cdl3outside"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdl3starsinsouth"),
        "historical",
        ["country", "days_since_bearish_cdl3starsinsouth"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlthrusting"),
        "historical",
        ["country", "days_since_bearish_cdlthrusting"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdltristar"),
        "historical",
        ["country", "days_since_bearish_cdltristar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlunique3river"),
        "historical",
        ["country", "days_since_bearish_cdlunique3river"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_country_days_since_bearish_cdlxsidegap3methods"),
        "historical",
        ["country", "days_since_bearish_cdlxsidegap3methods"],
        unique=False,
    )

    op.execute("ALTER TABLE historical SET (fillfactor=90);")

    # After the table is filled, you should run this (just for performance, not needed in development)
    # CLUSTER historical USING ix_historical_country_date;
    # ANALYZE historical;

    op.create_table(
        "screening_ticker",
        sa.Column("date", sa.DATE, nullable=False),
        sa.Column("growth", sa.FLOAT, nullable=True),
        sa.Column("country", sa.VARCHAR, nullable=True),
        sa.Column("ticker", sa.VARCHAR, nullable=False),
        sa.Column("name", sa.VARCHAR, nullable=True),
        sa.Column("industry", sa.VARCHAR, nullable=True),
        sa.Column("sector", sa.VARCHAR, nullable=True),
        sa.Column("close", sa.REAL, nullable=True),
        sa.Column("change_percent", sa.REAL, nullable=True),
        sa.Column("volume", sa.REAL, nullable=True),
        sa.Column("turnover_percent", sa.REAL, nullable=True),
        sa.Column("range_percent", sa.REAL, nullable=True),
        sa.Column("year_high_rel", sa.REAL, nullable=True),
        sa.Column("year_low_rel", sa.REAL, nullable=True),
        sa.Column("market_cap", sa.REAL, nullable=True),
        sa.Column("eps", sa.REAL, nullable=True),
        sa.Column("dps", sa.REAL, nullable=True),
        sa.Column("dividend_yield_percent", sa.REAL, nullable=True),
        sa.Column("book_value", sa.REAL, nullable=True),
        sa.Column("pb", sa.REAL, nullable=True),
        sa.Column("ps", sa.REAL, nullable=True),
        sa.Column("pe", sa.REAL, nullable=True),
        sa.Column("peg", sa.REAL, nullable=True),
        sa.Column("pcf", sa.REAL, nullable=True),
        sa.Column("evs", sa.REAL, nullable=True),
        sa.Column("evebitda", sa.REAL, nullable=True),
        sa.Column("evebit", sa.REAL, nullable=True),
        sa.Column("evnopat", sa.REAL, nullable=True),
        sa.Column("ebitda_margin", sa.REAL, nullable=True),
        sa.Column("ebit_margin", sa.REAL, nullable=True),
        sa.Column("profit_margin", sa.REAL, nullable=True),
        sa.Column("revenue_5y_cagr", sa.REAL, nullable=True),
        sa.Column("ebitda_5y_cagr", sa.REAL, nullable=True),
        sa.Column("ebit_5y_cagr", sa.REAL, nullable=True),
        sa.Column("profit_5y_cagr", sa.REAL, nullable=True),
        sa.Column("roe", sa.REAL, nullable=True),
        sa.Column("roa", sa.REAL, nullable=True),
        sa.Column("roce", sa.REAL, nullable=True),
        sa.Column("roic", sa.REAL, nullable=True),
        sa.Column("rod", sa.REAL, nullable=True),
        sa.Column("current_ratio", sa.REAL, nullable=True),
        sa.Column("quick_ratio", sa.REAL, nullable=True),
        sa.Column("cash_ratio", sa.REAL, nullable=True),
        sa.Column("ocf_ratio", sa.REAL, nullable=True),
        sa.Column("wct", sa.REAL, nullable=True),
        sa.Column("de", sa.REAL, nullable=True),
        sa.Column("da", sa.REAL, nullable=True),
        sa.Column("ea", sa.REAL, nullable=True),
        sa.Column("piotroski", sa.SMALLINT, nullable=True),
        sa.Column("altman_z", sa.REAL, nullable=True),
        sa.Column("grade", sa.REAL, nullable=True),
        sa.Column("ownership_percent", sa.REAL, nullable=True),
        sa.Column("ownership_percent_change", sa.REAL, nullable=True),
        sa.Column("put_call_ratio", sa.REAL, nullable=True),
        sa.Column("put_call_ratio_change", sa.REAL, nullable=True),
        sa.Column("ao", sa.REAL, nullable=True),
        sa.Column("rsi", sa.REAL, nullable=True),
        sa.Column("stoch", sa.REAL, nullable=True),
        sa.Column("tsi", sa.REAL, nullable=True),
        sa.Column("uo", sa.REAL, nullable=True),
        sa.Column("cmf", sa.REAL, nullable=True),
        sa.Column("fi", sa.REAL, nullable=True),
        sa.Column("mfi", sa.REAL, nullable=True),
        sa.Column("nvi", sa.REAL, nullable=True),
        sa.Column("adx", sa.REAL, nullable=True),
        sa.Column("adxp", sa.REAL, nullable=True),
        sa.Column("adxn", sa.REAL, nullable=True),
        sa.Column("macd", sa.REAL, nullable=True),
        sa.Column("mi", sa.REAL, nullable=True),
        sa.Column("kdj", sa.REAL, nullable=True),
        sa.Column("pvol", sa.REAL, nullable=True),
        sa.Column("stdev", sa.REAL, nullable=True),
        sa.Column("entropy", sa.REAL, nullable=True),
        sa.Column("skew", sa.REAL, nullable=True),
        sa.Column("kurtosis", sa.REAL, nullable=True),
        sa.Column("sma", sa.REAL, nullable=True),
        sa.Column("ema", sa.REAL, nullable=True),
        sa.Column("kama", sa.REAL, nullable=True),
        sa.Column("bollh", sa.REAL, nullable=True),
        sa.Column("bolll", sa.REAL, nullable=True),
        sa.Column("dch", sa.REAL, nullable=True),
        sa.Column("dcl", sa.REAL, nullable=True),
        sa.Column("kch", sa.REAL, nullable=True),
        sa.Column("kcl", sa.REAL, nullable=True),
        sa.Column("days_since_bullish_cdlbreakaway", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlcounterattack", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdldojistar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdldragonflydoji", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlengulfing", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlhammer", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlhomingpigeon", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlinvertedhammer", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlladderbottom", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdllongline", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlmarubozu", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlmatchinglow", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlmorningdojistar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlonneck", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlpiercing", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlseparatinglines", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdl3whitesoldiers", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdl3inside", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdl3outside", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdl3starsinsouth", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlthrusting", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdltristar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlunique3river", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bullish_cdlxsidegap3methods", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlbreakaway", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlcounterattack", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdldojistar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdldragonflydoji", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlengulfing", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlhammer", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlhomingpigeon", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlinvertedhammer", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlladderbottom", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdllongline", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlmarubozu", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlmatchinglow", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlmorningdojistar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlonneck", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlpiercing", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlseparatinglines", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdl3whitesoldiers", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdl3inside", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdl3outside", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdl3starsinsouth", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlthrusting", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdltristar", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlunique3river", sa.SMALLINT, nullable=True),
        sa.Column("days_since_bearish_cdlxsidegap3methods", sa.SMALLINT, nullable=True),
        sa.PrimaryKeyConstraint("ticker"),
    )

    op.create_index(
        op.f("ix_screening_ticker_country_date"),
        "screening_ticker",
        ["country", "date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_industry"),
        "screening_ticker",
        ["country", "industry"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_sector"),
        "screening_ticker",
        ["country", "sector"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_close"),
        "screening_ticker",
        ["country", "close"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_change_percent"),
        "screening_ticker",
        ["country", "change_percent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_volume"),
        "screening_ticker",
        ["country", "volume"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_turnover_percent"),
        "screening_ticker",
        ["country", "turnover_percent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_range_percent"),
        "screening_ticker",
        ["country", "range_percent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_year_high_rel"),
        "screening_ticker",
        ["country", "year_high_rel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_year_low_rel"),
        "screening_ticker",
        ["country", "year_low_rel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_market_cap"),
        "screening_ticker",
        ["country", "market_cap"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_eps"),
        "screening_ticker",
        ["country", "eps"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_dps"),
        "screening_ticker",
        ["country", "dps"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_dividend_yield_percent"),
        "screening_ticker",
        ["country", "dividend_yield_percent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_book_value"),
        "screening_ticker",
        ["country", "book_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_pb"),
        "screening_ticker",
        ["country", "pb"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_ps"),
        "screening_ticker",
        ["country", "ps"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_pe"),
        "screening_ticker",
        ["country", "pe"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_peg"),
        "screening_ticker",
        ["country", "peg"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_pcf"),
        "screening_ticker",
        ["country", "pcf"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_evs"),
        "screening_ticker",
        ["country", "evs"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_evebitda"),
        "screening_ticker",
        ["country", "evebitda"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_evebit"),
        "screening_ticker",
        ["country", "evebit"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_evnopat"),
        "screening_ticker",
        ["country", "evnopat"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_ebitda_margin"),
        "screening_ticker",
        ["country", "ebitda_margin"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_ebit_margin"),
        "screening_ticker",
        ["country", "ebit_margin"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_profit_margin"),
        "screening_ticker",
        ["country", "profit_margin"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_revenue_5y_cagr"),
        "screening_ticker",
        ["country", "revenue_5y_cagr"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_ebitda_5y_cagr"),
        "screening_ticker",
        ["country", "ebitda_5y_cagr"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_ebit_5y_cagr"),
        "screening_ticker",
        ["country", "ebit_5y_cagr"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_profit_5y_cagr"),
        "screening_ticker",
        ["country", "profit_5y_cagr"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_roe"),
        "screening_ticker",
        ["country", "roe"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_roa"),
        "screening_ticker",
        ["country", "roa"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_roce"),
        "screening_ticker",
        ["country", "roce"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_roic"),
        "screening_ticker",
        ["country", "roic"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_rod"),
        "screening_ticker",
        ["country", "rod"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_current_ratio"),
        "screening_ticker",
        ["country", "current_ratio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_quick_ratio"),
        "screening_ticker",
        ["country", "quick_ratio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_cash_ratio"),
        "screening_ticker",
        ["country", "cash_ratio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_ocf_ratio"),
        "screening_ticker",
        ["country", "ocf_ratio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_wct"),
        "screening_ticker",
        ["country", "wct"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_de"),
        "screening_ticker",
        ["country", "de"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_da"),
        "screening_ticker",
        ["country", "da"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_ea"),
        "screening_ticker",
        ["country", "ea"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_piotroski"),
        "screening_ticker",
        ["country", "piotroski"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_altman_z"),
        "screening_ticker",
        ["country", "altman_z"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_grade"),
        "screening_ticker",
        ["country", "grade"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_ownership_percent"),
        "screening_ticker",
        ["country", "ownership_percent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_ownership_percent_change"),
        "screening_ticker",
        ["country", "ownership_percent_change"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_put_call_ratio"),
        "screening_ticker",
        ["country", "put_call_ratio"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_put_call_ratio_change"),
        "screening_ticker",
        ["country", "put_call_ratio_change"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_ao"),
        "screening_ticker",
        ["country", "ao"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_rsi"),
        "screening_ticker",
        ["country", "rsi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_stoch"),
        "screening_ticker",
        ["country", "stoch"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_tsi"),
        "screening_ticker",
        ["country", "tsi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_uo"),
        "screening_ticker",
        ["country", "uo"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_cmf"),
        "screening_ticker",
        ["country", "cmf"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_fi"),
        "screening_ticker",
        ["country", "fi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_mfi"),
        "screening_ticker",
        ["country", "mfi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_nvi"),
        "screening_ticker",
        ["country", "nvi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_adx"),
        "screening_ticker",
        ["country", "adx"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_adxp"),
        "screening_ticker",
        ["country", "adxp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_adxn"),
        "screening_ticker",
        ["country", "adxn"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_macd"),
        "screening_ticker",
        ["country", "macd"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_mi"),
        "screening_ticker",
        ["country", "mi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_kdj"),
        "screening_ticker",
        ["country", "kdj"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_pvol"),
        "screening_ticker",
        ["country", "pvol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_stdev"),
        "screening_ticker",
        ["country", "stdev"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_entropy"),
        "screening_ticker",
        ["country", "entropy"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_skew"),
        "screening_ticker",
        ["country", "skew"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_kurtosis"),
        "screening_ticker",
        ["country", "kurtosis"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_sma"),
        "screening_ticker",
        ["country", "sma"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_ema"),
        "screening_ticker",
        ["country", "ema"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_kama"),
        "screening_ticker",
        ["country", "kama"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_bollh"),
        "screening_ticker",
        ["country", "bollh"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_bolll"),
        "screening_ticker",
        ["country", "bolll"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_dch"),
        "screening_ticker",
        ["country", "dch"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_dcl"),
        "screening_ticker",
        ["country", "dcl"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_kch"),
        "screening_ticker",
        ["country", "kch"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_kcl"),
        "screening_ticker",
        ["country", "kcl"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlbreakaway"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlbreakaway"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlcounterattack"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlcounterattack"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdldojistar"),
        "screening_ticker",
        ["country", "days_since_bullish_cdldojistar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdldragonflydoji"),
        "screening_ticker",
        ["country", "days_since_bullish_cdldragonflydoji"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlengulfing"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlengulfing"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlhammer"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlhammer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlhomingpigeon"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlhomingpigeon"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlinvertedhammer"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlinvertedhammer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlladderbottom"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlladderbottom"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdllongline"),
        "screening_ticker",
        ["country", "days_since_bullish_cdllongline"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlmarubozu"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlmarubozu"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlmatchinglow"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlmatchinglow"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlmorningdojistar"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlmorningdojistar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlonneck"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlonneck"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlpiercing"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlpiercing"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlseparatinglines"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlseparatinglines"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdl3whitesoldiers"),
        "screening_ticker",
        ["country", "days_since_bullish_cdl3whitesoldiers"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdl3inside"),
        "screening_ticker",
        ["country", "days_since_bullish_cdl3inside"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdl3outside"),
        "screening_ticker",
        ["country", "days_since_bullish_cdl3outside"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdl3starsinsouth"),
        "screening_ticker",
        ["country", "days_since_bullish_cdl3starsinsouth"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlthrusting"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlthrusting"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdltristar"),
        "screening_ticker",
        ["country", "days_since_bullish_cdltristar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlunique3river"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlunique3river"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bullish_cdlxsidegap3methods"),
        "screening_ticker",
        ["country", "days_since_bullish_cdlxsidegap3methods"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlbreakaway"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlbreakaway"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlcounterattack"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlcounterattack"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdldojistar"),
        "screening_ticker",
        ["country", "days_since_bearish_cdldojistar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdldragonflydoji"),
        "screening_ticker",
        ["country", "days_since_bearish_cdldragonflydoji"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlengulfing"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlengulfing"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlhammer"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlhammer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlhomingpigeon"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlhomingpigeon"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlinvertedhammer"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlinvertedhammer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlladderbottom"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlladderbottom"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdllongline"),
        "screening_ticker",
        ["country", "days_since_bearish_cdllongline"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlmarubozu"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlmarubozu"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlmatchinglow"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlmatchinglow"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlmorningdojistar"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlmorningdojistar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlonneck"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlonneck"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlpiercing"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlpiercing"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlseparatinglines"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlseparatinglines"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdl3whitesoldiers"),
        "screening_ticker",
        ["country", "days_since_bearish_cdl3whitesoldiers"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdl3inside"),
        "screening_ticker",
        ["country", "days_since_bearish_cdl3inside"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdl3outside"),
        "screening_ticker",
        ["country", "days_since_bearish_cdl3outside"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdl3starsinsouth"),
        "screening_ticker",
        ["country", "days_since_bearish_cdl3starsinsouth"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlthrusting"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlthrusting"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdltristar"),
        "screening_ticker",
        ["country", "days_since_bearish_cdltristar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlunique3river"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlunique3river"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_ticker_country_days_since_bearish_cdlxsidegap3methods"),
        "screening_ticker",
        ["country", "days_since_bearish_cdlxsidegap3methods"],
        unique=False,
    )

    # ALTER TABLE command takes a long time and implements an exclusive lock. To avoid interference with the script in pre_seed_db.py, we wait for the command to finish.


def downgrade() -> None:
    pass
